### ISSUE TITLE
TypeError: Cannot read property '_owner' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#1059]
https://sentry.io/ringteki-team/ringteki/issues/403048478/

```
TypeError: Cannot read property '_owner' of undefined
  at getReactComponentFromDOMNode (./client/GameComponents/Card.jsx:64:49)
  at onTouchEnd (./client/GameComponents/Card.jsx:92:38)
  at apply (./client/GameComponents/Card.jsx:309:41)
  at Array.forEach (<anonymous>)
...
(13 additional frame(s) were not displayed)
```

**Comment by jeremylarner** [comment]
This seems to be fixed
