### ISSUE TITLE
TypeError: Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#116]
https://sentry.io/ringteki-team/ringteki/issues/352413383/

```
TypeError: Cannot read property 'uuid' of undefined
  at onCardClick (./client/GameBoard.jsx:196:55)
  at onClick (./client/GameComponents/CardCollection.jsx:57:27)
  at onClick (./client/GameComponents/Card.jsx:121:23)
  at func (./client/GameComponents/Card.jsx:309:41)
  at Array.forEach (<anonymous>)
...
(15 additional frame(s) were not displayed)
```

**Comment by jeremylarner** [comment]
Fix submitted #488
