### ISSUE TITLE
Error trying to transferHonor in single player

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#129]
2017-09-23T19:36:44.583Z - error:  TypeError: Cannot read property 'honor' of undefined
    at Game.transferHonor (/home/debian/gamenode/server/game/game.js:398:9)
    at Player.resolveAirRing (/home/debian/gamenode/server/game/player.js:1264:23)
    at MenuPrompt.onMenuCommand (/home/debian/gamenode/server/game/gamesteps/menuprompt.js:49:32)
    at GamePipeline.handleMenuCommand (/home/debian/gamenode/server/game/gamepipeline.js:77:21)
    at EventWindow.onMenuCommand (/home/debian/gamenode/server/game/gamesteps/eventwindow.js:38:30)
    at GamePipeline.handleMenuCommand (/home/debian/gamenode/server/game/gamepipeline.js:77:21)
    at ConflictFlow.onMenuCommand (/home/debian/gamenode/server/game/gamesteps/conflict/conflictflow.js:350:30)
    at GamePipeline.handleMenuCommand (/home/debian/gamenode/server/game/gamepipeline.js:77:21)
    at ConflictPhase.onMenuCommand (/home/debian/gamenode/server/game/gamesteps/phase.js:32:30)
    at GamePipeline.handleMenuCommand (/home/debian/gamenode/server/game/gamepipeline.js:77:21)
    at Game.menuButton (/home/debian/gamenode/server/game/game.js:580:26)
    at runAndCatchErrors (/home/debian/gamenode/server/gamenode/gameserver.js:343:26)
    at GameServer.runAndCatchErrors (/home/debian/gamenode/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/gamenode/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/gamenode/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/gamenode/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/gamenode/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/gamenode/node_modules/raven/lib/client.js:159:49)
    at /home/debian/gamenode/node_modules/raven/lib/client.js:255:12
    at /home/debian/gamenode/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/gamenode/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)

**Comment by jeremylarner** [comment]
Fix submitted
