### ISSUE TITLE
Crash when using Earth ring in singleplayer

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#130]
2017-09-23T19:34:07.836Z - error:  TypeError: Cannot read property 'discardAtRandom' of undefined
    at Player.resolveRingEffects (/home/debian/gamenode/server/game/player.js:1209:28)
    at EventWindow.game.raiseEvent [as handler] (/home/debian/gamenode/server/game/gamesteps/conflict/conflictflow.js:301:24)
    at EventWindow.executeHandler (/home/debian/gamenode/server/game/gamesteps/eventwindow.js:84:18)
    at SimpleStep.EventWindow.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/gamenode/server/game/gamesteps/eventwindow.js:19:45)
    at SimpleStep.continue (/home/debian/gamenode/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/gamenode/server/game/gamepipeline.js:91:36)
    at EventWindow.continue (/home/debian/gamenode/server/game/gamesteps/eventwindow.js:46:38)
    at GamePipeline.continue (/home/debian/gamenode/server/game/gamepipeline.js:91:36)
    at ConflictFlow.continue (/home/debian/gamenode/server/game/gamesteps/conflict/conflictflow.js:362:65)
    at GamePipeline.continue (/home/debian/gamenode/server/game/gamepipeline.js:91:36)
    at ConflictPhase.continue (/home/debian/gamenode/server/game/gamesteps/phase.js:40:38)
    at GamePipeline.continue (/home/debian/gamenode/server/game/gamepipeline.js:91:36)
    at Game.continue (/home/debian/gamenode/server/game/game.js:902:31)
    at runAndCatchErrors (/home/debian/gamenode/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/gamenode/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/gamenode/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/gamenode/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/gamenode/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/gamenode/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/gamenode/node_modules/raven/lib/client.js:159:49)
    at /home/debian/gamenode/node_modules/raven/lib/client.js:255:12
    at /home/debian/gamenode/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/gamenode/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)
error: Forever detected script exited with code: 1

**Comment by jeremylarner** [comment]
Fix submitted
