### ISSUE TITLE
Game crashed attaching Ornate Fan

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#152]
2017-09-25T17:21:33.303Z - error:  TypeError: originalParent.removeAttachment is not a function
    at Player.attach (/home/debian/node-1/server/game/player.js:665:28)
    at PlayAttachmentAction.executeHandler (/home/debian/node-1/server/game/playattachmentaction.js:39:22)
    at AbilityResolver.executeHandler (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:133:26)
    at SimpleStep.AbilityResolver.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:24:45)
    at SimpleStep.continue (/home/debian/node-1/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:52:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at ConflictFlow.continue (/home/debian/node-1/server/game/gamesteps/conflict/conflictflow.js:362:65)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at ConflictPhase.continue (/home/debian/node-1/server/game/gamesteps/phase.js:40:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at Game.continue (/home/debian/node-1/server/game/game.js:910:31)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by jeremylarner** [comment]
Somehow an attachment which already has a parent is being attached to something else (seems to not be a card, as it doesn't have the relevant function) That shouldn't be possible at the moment because parent should be cleared whenever the attachment leaves play. I'll check that there isn't some way an attachment can leave play without clearing its parent

**Comment by jeremylarner** [comment]
I tried to work out what could have led to this, but I can't find any potential causes.  Can you keep an eye out for similar crashes and post them here?
