### ISSUE TITLE
TypeError: Cannot read property 'performed' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#162]
2017-09-26T02:03:06.507Z - error:  TypeError: Cannot read property 'performed' of undefined
    at ConflictTracker.perform (/home/debian/node-2/server/game/conflicttracker.js:121:28)
    at ConflictFlow.initiateConflict (/home/debian/node-2/server/game/gamesteps/conflict/conflictflow.js:58:49)
    at SimpleStep.ConflictFlow.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-2/server/game/gamesteps/conflict/conflictflow.js:31:50)
    at SimpleStep.continue (/home/debian/node-2/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:91:36)
    at ConflictFlow.continue (/home/debian/node-2/server/game/gamesteps/conflict/conflictflow.js:345:65)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:91:36)
    at ConflictPhase.continue (/home/debian/node-2/server/game/gamesteps/phase.js:40:38)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:91:36)
    at Game.continue (/home/debian/node-2/server/game/game.js:912:31)
    at runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-2/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-2/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-2/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-2/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/node-2/node_modules/raven/lib/client.js:159:49)
    at /home/debian/node-2/node_modules/raven/lib/client.js:255:12
    at /home/debian/node-2/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/node-2/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)

**Comment by jeremylarner** [comment]
I think this is probably that a conflict has somehow been initiated without a conflict type.  That shouldn't happen - in order to leave the initiate conflict prompt you need to either choose a ring (and therefore a conflict type) or pass, in which case the conflict should be cancelled and this code shouldn't run.

**Comment by jeremylarner** [comment]
This error happens when you click pass on the intiate conflict window too quickly, still not sure what causes it though
