### ISSUE TITLE
error:  TypeError: this.targets.every is not a function

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#359]
2017-10-10T20:45:05.253Z - error:  TypeError: this.targets.every is not a function
    at PlayAttachmentAction.canResolveTargets (/home/debian/node-1/server/game/baseability.js:131:29)
    at _.filter.action (/home/debian/node-1/server/game/player.js:582:144)
    at /home/debian/node-1/nodemodules/underscore/underscore.js:227:11
    at Function..each._.forEach (/home/debian/node-1/nodemodules/underscore/underscore.js:153:9)
    at Function..filter._.select (/home/debian/node-1/node_modules/underscore/underscore.js:226:7)
    at Player.playCard (/home/debian/node-1/server/game/player.js:582:29)
    at Game.cardClicked (/home/debian/node-1/server/game/game.js:220:134)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:343:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-1/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/node-1/node_modules/raven/lib/client.js:159:49)
    at /home/debian/node-1/node_modules/raven/lib/client.js:255:12
    at /home/debian/node-1/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/node-1/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)

**Comment by jeremylarner** [comment]
Fix submitted #361
