### ISSUE TITLE
error:  TypeError: Cannot read property 'dishonorCharacter' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#360]
2017-10-10T20:54:45.390Z - error:  TypeError: Cannot read property 'dishonorCharacter' of undefined
    at handler (/home/debian/node-1/server/game/cards/01 - Core/ForgedEdict.js:12:112)
    at CardInterrupt.executeHandler (/home/debian/node-1/server/game/promptedtriggeredability.js:62:23)
    at AbilityResolver.executeHandler (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:143:22)
    at SimpleStep.AbilityResolver.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:26:45)
    at SimpleStep.continue (/home/debian/node-1/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:58:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at InitiateAbilityEventWindow.continue (/home/debian/node-1/server/game/gamesteps/initiateabilityeventwindow.js:47:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:58:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at ConflictFlow.continue (/home/debian/node-1/server/game/gamesteps/conflict/conflictflow.js:374:65)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at ConflictPhase.continue (/home/debian/node-1/server/game/gamesteps/phase.js:44:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at Game.continue (/home/debian/node-1/server/game/game.js:909:31)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-1/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/node-1/node_modules/raven/lib/client.js:159:49)
    at /home/debian/node-1/node_modules/raven/lib/client.js:255:12
    at /home/debian/node-1/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/node-1/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:505:3)

**Comment by jeremylarner** [comment]
Fix submitted #362
