### ISSUE TITLE
error:  TypeError: Cannot read property 'getNumberOfCardsInPlay' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#396]
2017-10-11T04:59:46.816Z - error:  TypeError: Cannot read property 'getNumberOfCardsInPlay' of undefined
    at onCardAbilityInitiated (/home/debian/node-1/server/game/cards/01 - Core/VoiceOfHonor.js:7:189)
    at CardInterrupt.isTriggeredByEvent (/home/debian/node-1/server/game/triggeredability.js:55:16)
    at CardInterrupt.eventHandler (/home/debian/node-1/server/game/triggeredability.js:37:18)
    at Game.handler (/home/debian/node-1/server/game/triggeredability.js:133:40)
    at emitTwo (events.js:125:13)
    at Game.emit (events.js:213:7)
    at _.each.event (/home/debian/node-1/server/game/gamesteps/baseabilitywindow.js:19:23)
    at Function._.each._.forEach (/home/debian/node-1/node_modules/underscore/underscore.js:153:9)
    at TriggeredAbilityWindow.emitEvents (/home/debian/node-1/server/game/gamesteps/baseabilitywindow.js:18:11)
    at Game.openAbilityWindow (/home/debian/node-1/server/game/game.js:688:16)
    at InitiateAbilityEventWindow.cancelInterrupts (/home/debian/node-1/server/game/gamesteps/initiateabilityeventwindow.js:51:19)
    at SimpleStep.InitiateAbilityEventWindow.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-1/server/game/gamesteps/initiateabilityeventwindow.js:15:45)
    at SimpleStep.continue (/home/debian/node-1/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at InitiateAbilityEventWindow.continue (/home/debian/node-1/server/game/gamesteps/initiateabilityeventwindow.js:47:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:58:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at DrawPhase.continue (/home/debian/node-1/server/game/gamesteps/phase.js:44:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at Game.continue (/home/debian/node-1/server/game/game.js:909:31)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-1/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);

**Comment by jeremylarner** [comment]
Fixed by #402
