### ISSUE TITLE
error:  TypeError: originalParent.removeAttachment is  not a function

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#398]
2017-10-10T20:28:01.861Z - error:  TypeError: originalParent.removeAttachment is
 not a function
    at Player.attach (/home/debian/node-2/server/game/player.js:685:28)
    at Object.onSelect (/home/debian/node-2/server/game/gamesteps/attachmentprompt.js:17:30)
    at SelectCardPrompt.fireOnSelect (/home/debian/node-2/server/game/gamesteps/selectcardprompt.js:181:28)
    at SelectCardPrompt.onCardClicked (/home/debian/node-2/server/game/gamesteps/selectcardprompt.js:151:18)
    at GamePipeline.handleCardClicked (/home/debian/node-2/server/game/gamepipeline.js:66:21)
    at ConflictPhase.onCardClicked (/home/debian/node-2/server/game/gamesteps/phase.js:28:30)
    at GamePipeline.handleCardClicked (/home/debian/node-2/server/game/gamepipeline.js:66:21)
    at Game.cardClicked (/home/debian/node-2/server/game/game.js:215:26)
    at runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:343:26)
    at GameServer.runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-2/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-2/server/socket.js:51:13)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/debian/node-2/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-2/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);

**Comment by jeremylarner** [comment]
This is a bug in legacy throneteki code which shouldn't be running unless people are still dragging attachments into play instead of clicking them.  I'll have a look and see if I can work out what's causing it...
