### ISSUE TITLE
error:  TypeError: this.game.rings.find is not a function

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#399]
2017-10-11T10:03:20.529Z - error:  TypeError: this.game.rings.find is not a function
    at Conflict.switchType (/home/debian/node-2/server/game/conflict.js:95:36)
    at CardAction.handler (/home/debian/node-2/server/game/cards/01 - Core/CaptiveAudience.js:10:43)
    at CardAction.executeHandler (/home/debian/node-2/server/game/cardaction.js:145:28)
    at AbilityResolver.executeHandler (/home/debian/node-2/server/game/gamesteps/abilityresolver.js:143:22)
    at SimpleStep.AbilityResolver.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-2/server/game/gamesteps/abilityresolver.js:26:45)
    at SimpleStep.continue (/home/debian/node-2/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at AbilityResolver.continue (/home/debian/node-2/server/game/gamesteps/abilityresolver.js:58:42)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at ConflictFlow.continue (/home/debian/node-2/server/game/gamesteps/conflict/conflictflow.js:374:65)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at ConflictPhase.continue (/home/debian/node-2/server/game/gamesteps/phase.js:44:38)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at Game.continue (/home/debian/node-2/server/game/game.js:909:31)
    at runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-2/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-2/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-2/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-2/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);

**Comment by jeremylarner** [comment]
Fixed by #370
