### ISSUE TITLE
Seppun Guardsman - error:  TypeError: Cannot read property 'imperialFavor' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#448]
2017-10-13T00:57:11.395Z - error:  TypeError: Cannot read property 'imperialFavor' of undefined
    at Effect.condition (/home/debian/node-1/server/game/cards/01 - Core/SeppunGuardsman.js:6:71)
    at Effect.addTargets (/home/debian/node-1/server/game/effect.js:72:34)
    at EffectEngine.add (/home/debian/node-1/server/game/effectengine.js:22:16)
    at Game.addEffect (/home/debian/node-1/server/game/game.js:165:27)
    at _.each.effect (/home/debian/node-1/server/game/basecard.js:280:27)
    at Function._.each._.forEach (/home/debian/node-1/node_modules/underscore/underscore.js:153:9)
    at SeppunGuardsman.applyPersistentEffects (/home/debian/node-1/server/game/basecard.js:278:11)
    at Player.putIntoPlay (/home/debian/node-1/server/game/player.js:640:14)
    at DynastyCardAction.executeHandler (/home/debian/node-1/server/game/dynastycardaction.js:34:24)
    at AbilityResolver.executeHandler (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:145:22)
    at SimpleStep.AbilityResolver.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:27:45)
    at SimpleStep.continue (/home/debian/node-1/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:59:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at DynastyPhase.continue (/home/debian/node-1/server/game/gamesteps/phase.js:44:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:102:36)
    at Game.continue (/home/debian/node-1/server/game/game.js:920:31)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
2017-10-13T00:57:11.404Z - error:  TypeError: Cannot read property 'imperialFavor' of undefined
    at Effect.condition (/home/debian/node-1/server/game/cards/01 - Core/SeppunGuardsman.js:6:71)
    at Effect.reapply (/home/debian/node-1/server/game/effect.js:173:37)
    at _.each.effect (/home/debian/node-1/server/game/effectengine.js:37:24)
    at Function._.each._.forEach (/home/debian/node-1/node_modules/underscore/underscore.js:153:9)
    at EffectEngine.reapplyStateDependentEffects (/home/debian/node-1/server/game/effectengine.js:35:11)
    at Game.continue (/home/debian/node-1/server/game/game.js:921:27)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:342:14)

**Comment by jeremylarner** [comment]
Fixed in #424
