### ISSUE TITLE
error:  TypeError: this.properties.handlers[arg] is not a function

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#457]
2017-10-13T16:25:00.380Z - error:  TypeError: this.properties.handlers[arg] is not a function
    at HandlerMenuPrompt.onMenuCommand (/home/debian/node-2/server/game/gamesteps/handlermenuprompt.js:52:38)
    at GamePipeline.handleMenuCommand (/home/debian/node-2/server/game/gamepipeline.js:88:21)
    at AbilityResolver.onMenuCommand (/home/debian/node-2/server/game/gamesteps/abilityresolver.js:50:30)
    at GamePipeline.handleMenuCommand (/home/debian/node-2/server/game/gamepipeline.js:88:21)
    at ConflictFlow.onMenuCommand (/home/debian/node-2/server/game/gamesteps/conflict/conflictflow.js:362:30)
    at GamePipeline.handleMenuCommand (/home/debian/node-2/server/game/gamepipeline.js:88:21)
    at ConflictPhase.onMenuCommand (/home/debian/node-2/server/game/gamesteps/phase.js:36:30)
    at GamePipeline.handleMenuCommand (/home/debian/node-2/server/game/gamepipeline.js:88:21)
    at Game.menuButton (/home/debian/node-2/server/game/game.js:583:26)
    at runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:343:26)
    at GameServer.runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-2/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-2/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-2/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by jeremylarner** [comment]
This has been fixed
