### ISSUE TITLE
error:  TypeError: Cannot read property 'isBroken' of undefined

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#464]
2017-10-14T11:20:46.791Z - error:  TypeError: Cannot read property 'isBroken' of undefined
    at _.each.location (/home/debian/node-2/server/game/player.js:200:28)
    at Function._.each._.forEach (/home/debian/node-2/node_modules/underscore/underscore.js:153:9)
    at Player.discardFromBrokenProvinces (/home/debian/node-2/server/game/player.js:197:11)
    at _.each.player (/home/debian/node-2/server/game/gamesteps/regroupphase.js:41:75)
    at Function._.each._.forEach (/home/debian/node-2/node_modules/underscore/underscore.js:153:9)
    at RegroupPhase.discardFromProvinces (/home/debian/node-2/server/game/gamesteps/regroupphase.js:41:11)
    at SimpleStep.RegroupPhase.initialise.SimpleStep [as continueFunc] (/home/debian/node-2/server/game/gamesteps/regroupphase.js:24:45)
    at SimpleStep.continue (/home/debian/node-2/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at RegroupPhase.continue (/home/debian/node-2/server/game/gamesteps/phase.js:44:38)
    at GamePipeline.continue (/home/debian/node-2/server/game/gamepipeline.js:102:36)
    at Game.continue (/home/debian/node-2/server/game/game.js:920:31)
    at runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:345:26)
    at GameServer.runAndCatchErrors (/home/debian/node-2/server/gamenode/gameserver.js:117:13)
    at GameServer.onGameMessage (/home/debian/node-2/server/gamenode/gameserver.js:342:14)
    at Socket.onSocketEvent (/home/debian/node-2/server/socket.js:51:13)
    at emitThree (events.js:135:13)
    at Socket.emit (events.js:216:7)
    at /home/debian/node-2/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by jeremylarner** [comment]
Fixed in #546
