### ISSUE TITLE
Possible issue with game node #1

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#93]
2017-09-20T14:26:30.161Z - error:  TypeError: context.source.play is not a function
    at PlayCardAction.executeHandler (/home/debian/node-1/server/game/playcardaction.js:25:24)
    at EventWindow.game.raiseEvent [as handler] (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:130:30)
    at EventWindow.executeHandler (/home/debian/node-1/server/game/gamesteps/eventwindow.js:84:18)
    at SimpleStep.EventWindow.pipeline.initialise.SimpleStep [as continueFunc] (/home/debian/node-1/server/game/gamesteps/eventwindow.js:19:45)
    at SimpleStep.continue (/home/debian/node-1/server/game/gamesteps/simplestep.js:10:21)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at EventWindow.continue (/home/debian/node-1/server/game/gamesteps/eventwindow.js:46:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at AbilityResolver.continue (/home/debian/node-1/server/game/gamesteps/abilityresolver.js:52:42)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at DrawPhase.continue (/home/debian/node-1/server/game/gamesteps/phase.js:40:38)
    at GamePipeline.continue (/home/debian/node-1/server/game/gamepipeline.js:91:36)
    at Game.continue (/home/debian/node-1/server/game/game.js:866:31)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:339:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:116:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:336:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-1/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/node-1/node_modules/raven/lib/client.js:159:49)
    at /home/debian/node-1/node_modules/raven/lib/client.js:255:12
    at /home/debian/node-1/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/node-1/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)

**Comment by jeremylarner** [comment]
This bug has been fixed.
