### ISSUE TITLE
Possible issue with game node #2

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#94]
2017-09-21T05:38:16.158Z - error:  TypeError: Cannot read property 'each' of undefined
    at Player.moveCard (/home/debian/node-1/server/game/player.js:999:29)
    at Player.drop (/home/debian/node-1/server/game/player.js:813:18)
    at Game.drop (/home/debian/node-1/server/game/game.js:353:19)
    at runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:337:26)
    at GameServer.runAndCatchErrors (/home/debian/node-1/server/gamenode/gameserver.js:116:13)
    at GameServer.onGameMessage (/home/debian/node-1/server/gamenode/gameserver.js:336:14)
    at Socket.onSocketEvent (/home/debian/node-1/server/socket.js:51:13)
    at emitMany (events.js:146:13)
    at Socket.emit (events.js:223:7)
    at /home/debian/node-1/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
/home/debian/node-1/node_modules/raven/lib/client.js:159
    kwargs.user = extend({}, this._globalContext.user, domainContext.user, kwargs.user);
                                                ^

TypeError: Cannot read property 'user' of undefined
    at Raven.process (/home/debian/node-1/node_modules/raven/lib/client.js:159:49)
    at /home/debian/node-1/node_modules/raven/lib/client.js:255:12
    at /home/debian/node-1/node_modules/raven/lib/parsers.js:52:5
    at /home/debian/node-1/node_modules/raven/lib/utils.js:211:30
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:504:3)

**Comment by jeremylarner** [comment]
This is happening because a BaseCard object is being moved from the play area to somewhere else.  BaseCards (provinces, strongholds and role cards) should never be in play, but if players drag them into play by accident, and then try and fix their mistake, it will throw this error.

**Comment by jeremylarner** [comment]
This has been fixed
